### ISSUE TITLE
Would it be possible to use SANSA-RDF & SANSA-Query in PySpark?

### ISSUE THREAD

**Issue by snamburi12** [SANSA-Stack/SANSA-Examples#27]
Hello,

I am interested in using SANSA API and I hope you can help me.

I am planning to use SANSA-RDF for reading turtle RDF/XML files into Spark and query using SANSA-Query library. Would it be possible to develop PySpark (python) code using theses libraries? Are there any PySpark (python) examples?

Thanks

**Comment by snamburi12** [comment]
I really appreciate if any one can share their suggestions & thoughts...

**Comment by GezimSejdiu** [comment]
Hi @snamburi12 ,

we thank you for reaching out and using SANSA. We (core team of SANSA) have thought about having a pySANSA version as well and it is on our radar for the future. We started experimenting a bit with a python wrapper from Scala code into pySpark code but still, it is experimental. Right now, we are thinking more about having a full python implementation of each SANSA layers instead of using wrappers (performance wise), but we plan it for SANSA 0.6 release (June 2019). It's under discussion until then.

Many thanks for your understanding and we look forward to your feedback on using SANSA.

Best regards,
Gezim

**Comment by snamburi12** [comment]
Hi Gezim,

Thank you for replying to my post. 
Looking forward for SANSA 0.6, python implementation of SANSA layers.

Thanks,
Satish
